# Generated by Django 5.0 on 2025-02-10 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='titlee',
            new_name='title',
        ),
    ]
